INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('address', 'some other street');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('email', 'taahl@eyeconic.com');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('facebookUrl', 'eyeconic.f');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('instagramUrl', 'eyeconic.i');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('isCaptchaEnabled', 'no');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('isEmailConfirmationRequired', 'no');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('locationLatitude', '20.992552000000007');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('locationLongitude', '105.80503099999999');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('phoneNumber', '+84 944 22 35 28');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('siteLogo', '/assets/img/logo.png');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('siteTitle', 'Eyeconic Glasses Shop');
INSERT INTO eyeconic.Preferences (`Key`, Value) VALUES ('twitterUrl', 'eyeconic.t');